# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile is used for configuring the Docker Host vm with Vagrant and must be seen in relation to the
# Vagrantfile placed in root folder
# Maintainer: Ismar Slomic "ismar.slomic@accenture.com"

# Specify Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Create and configure the VM(s)
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |virtualbox|
    # Name of the virtual machine
    virtualbox.name = "docker-host"

    # Display the VirtualBox GUI when booting the machine. Uncomment line below first
    # virtualbox.gui = true

    # Customize the amount of memory on the VM to 4 GB
    virtualbox.memory = 4096

    # Customize the number of CPUs to 2
    virtualbox.cpus = 2

    # Reduce import time and space by basing on master VM. Note that vagrant will create two vms
    virtualbox.linked_clone = true if Vagrant::VERSION =~ /^1.8/

  end

  # Check for updates of Virtualbox Guest Additions
  config.vbguest.auto_update = false

  # Assign a friendly name to this host VM
  config.vm.hostname = "docker-host"

  # Skip checking for an updated Vagrant box
  config.vm.box_check_update = false

  # Always use Vagrant's default insecure key
  config.ssh.insert_key = false

  # Spin up a "host box" for use with the Docker provider
  # and then provision it with Docker
  config.vm.box = "ubuntu/trusty64"

  # Provision Docker (install Docker, pull Docker container, configure containers)
  # See https://www.vagrantup.com/docs/provisioning/docker.html
  config.vm.provision "docker"

  # The following line terminates all ssh connections. Therefore
  # Vagrant will be forced to reconnect.
  # That's a workaround to have the docker command in the PATH
  # see https://github.com/mitchellh/vagrant/issues/3998#issuecomment-60359659
  config.vm.provision "shell", inline: "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

  # Forward port 8080 to host machine
  config.vm.network "forwarded_port", guest: 49160, host: 49161

  # Disable synced folders (prevents an NFS error on "vagrant up")
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Setup shared volumes for source code
  config.vm.synced_folder "../src/", "/srv/www", type: "rsync"
end #Vagrant.configure